# Generated by Django 5.2.3 on 2025-06-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('isbn', models.CharField(max_length=200)),
                ('avtor', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='books/')),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
