# Generated by Django 5.2.3 on 2025-06-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_avtor_customuser_alter_books_avtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
