# Generated by Django 5.2.3 on 2025-06-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_books_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='avtor',
        ),
        migrations.RemoveField(
            model_name='books',
            name='file',
        ),
        migrations.RemoveField(
            model_name='books',
            name='photo',
        ),
    ]
