# Generated by Django 5.2.3 on 2025-06-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_remove_books_avtor_remove_books_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtor',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('READER', 'reader'), ('PUBLISHER', 'publisher')], default='READER', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
