# Generated by Django 5.2.3 on 2025-06-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_avtor_role_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('READER', 'reader'), ('PUBLISHER', 'publisher')], default='READER', max_length=20),
        ),
    ]
